# Generated by Django 4.2.6 on 2023-11-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_description", models.TextField()),
                ("product_image", models.ImageField(upload_to="")),
                ("product_category", models.CharField(max_length=50)),
                ("product_stock", models.IntegerField()),
                ("product_rating", models.IntegerField(blank=True, null=True)),
                ("product_reviews", models.JSONField(blank=True, null=True)),
                ("product_brand", models.CharField(max_length=50)),
                ("product_date_added", models.DateField()),
                ("product_date_modified", models.DateField()),
                ("product_status", models.BooleanField()),
                ("product_discount", models.IntegerField()),
                ("product_discount_price", models.IntegerField()),
                ("product_attributes", models.JSONField(blank=True, null=True)),
                ("product_search_terms", models.CharField(max_length=500)),
                (
                    "product_retailer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
