# Generated by Django 4.2.5 on 2023-10-14 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('per_item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10))

            ],
            options={
                'abstract': False,
            },
        ),
    ]
