# Generated by Django 4.2 on 2023-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.IntegerField(),
        ),
    ]
