# Generated by Django 4.2.5 on 2023-10-14 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('is_billed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
