version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: cartsquad
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_USER: root
          MYSQL_PASSWORD: testpassword
          
    steps:
      - checkout

      # Install project dependencies
      - run:
          name: Install project dependencies
          command: |
            pip install -r cartsquad/requirements.txt

      # Install MySQL CLI, create user, and grant necessary permissions
      - run:
          name: Install MySQL CLI
          command: |
            apt-get update && apt-get install -y default-mysql-client
            mysql --protocol=tcp -h 127.0.0.1 -u root -ptestpassword --execute="CREATE USER 'root'@'%'; GRANT ALL PRIVILEGES ON cartsquad.* TO 'root'@'%'; FLUSH PRIVILEGES;"

      # Test MySQL Connection
      - run:
          name: Test MySQL Connection
          command: |
            mysql --protocol=tcp -h 127.0.0.1 -u root -ptestpassword --execute="USE cartsquad; SELECT 1;"

      # Run tests
      - run:
          name: Run tests
          command: |
            python cartsquad/manage.py test apps.products.tests
            python cartsquad/manage.py test apps.cart.tests

workflows:
  version: 2
  build:
    jobs:
      - build
