version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: mysql:8.0
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: cartsquad
          MYSQL_USER: root
          MYSQL_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y default-mysql-client
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py apps.products.tests

workflows:
  version: 2
  build:
    jobs:
      - build
