version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run Django migrations
      - run:
          name: Run Migrations
          command: |
            python manage.py migrate

      # Run all Django tests
      - run:
          name: Run All Tests
          command: |
            python manage.py test
            python manage.py test apps.product.tests
            python manage.py test apps.cart.tests
            

workflows:
  version: 2
  build:
    jobs:
      - build
