version: 2.1

jobs:
  build_and_test:
    docker:
      - image: python:3.8
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: cartsquad
          MYSQL_ROOT_PASSWORD: testpassword

    steps:
      - checkout

      # Install project dependencies
      - run:
          name: Install project dependencies
          command: |
            pip install -r cartsquad/requirements.txt

      # Test MySQL Connection
      - run:
          name: Test MySQL Connection
          command: |
            apt-get update && apt-get install -y default-mysql-client
            mysql --protocol=tcp -h 127.0.0.1 -u root -ptestpassword --execute="USE cartsquad; SELECT 1;"

      # Run migrations
      - run:
          name: Run migrations
          command: |
            python cartsquad/manage.py makemigrations accounts
            python cartsquad/manage.py migrate accounts
            python cartsquad/manage.py makemigrations products 
            python cartsquad/manage.py migrate products  # Fixed the migrate command
            python cartsquad/manage.py makemigrations cart 
            python cartsquad/manage.py migrate cart  # Fixed the migrate command
            python cartsquad/manage.py makemigrations orders
            python cartsquad/manage.py migrate orders  # Fixed the migrate command
            python cartsquad/manage.py migrate

      # Run tests
      - run:
          name: Run tests
          command: |
            python cartsquad/manage.py test apps.products.tests
            python cartsquad/manage.py test apps.cart.tests

  deploy:
    docker:
      - image: docker:20.10.5

    steps:
      - checkout

      # Build Django application image
      - run:
          name: Build Django image
          command: |
            docker build -t $DOCKER_HUB_USERNAME/cartsquad:latest -f Dockerfile .

      # Test Django application
      - run:
          name: Run Django tests
          command: |
            docker run -e DJANGO_DB_HOST=db -e DJANGO_DB_PORT=3306 -e DJANGO_DB_NAME=cartsquad -e DJANGO_DB_USER=root -e DJANGO_DB_PASSWORD=testpassword $DOCKER_HUB_USERNAME/cartsquad:latest \
              python cartsquad/manage.py test apps.products.tests
            docker run -e DJANGO_DB_HOST=db -e DJANGO_DB_PORT=3306 -e DJANGO_DB_NAME=cartsquad -e DJANGO_DB_USER=root -e DJANGO_DB_PASSWORD=testpassword $DOCKER_HUB_USERNAME/cartsquad:latest \
              python cartsquad/manage.py test apps.cart.tests

      # Push Django image to Docker Hub
      - run:
          name: Push Django image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push $DOCKER_HUB_USERNAME/cartsquad:latest

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - deploy
