version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: cartsquad
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root  

    steps:
      - checkout

      # Set up MySQL database and user using environment variables
      - run:
          name: Set up MySQL
          command: |
            mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE $MYSQL_DATABASE;"
            mysql -h 127.0.0.1 -u root -proot -e "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
            mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';"
            mysql -h 127.0.0.1 -u root -proot -e "FLUSH PRIVILEGES;"

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r cartsquad/requirements.txt

      # Run Django migrations
      - run:
          name: Run Migrations
          command: |
            python cartsquad/manage.py migrate

      # Run all Django tests
      - run:
          name: Run All Tests
          command: |
            python cartsquad/manage.py test
            python cartsquad/manage.py test apps.product.tests
            python cartsquad/manage.py test apps.cart.tests

workflows:
  version: 2
  build:
    jobs:
      - build
