version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cartsquad
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -ppassw0rd cartsquad
            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="USE cartsquad;"
      - run:
          name: Install project dependencies
          command: |
            pip install -r cartsquad/requirements.txt
      - run:
          name: Run tests
          command: |
            python cartsquad/manage.py apps.products.tests
            python cartsquad/manage.py apps.carts.tests


workflows:
  version: 2
  build:
    jobs:
      - build
