version: 2.1

jobs:

  build:

    docker:
      - image: python:3.8
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword  
          MYSQL_DATABASE: cartsquad

    steps:
      - checkout
      
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run: 
          name: Run Migrations
          environment:
            MYSQL_USER: cartuser
            MYSQL_PASSWORD: cartpassword  
          command: python manage.py migrate

      - run:
          name: Run Tests
          environment:
            MYSQL_USER: cartuser
            MYSQL_PASSWORD: cartpassword
          command: |
            python manage.py test
            python manage.py test apps.product.tests
            python manage.py test apps.cart.tests

workflows:
  build:
    jobs:
      - build