version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: cartsquad
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
          
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install project dependencies
          command: |
            pip install -r cartsquad/requirements.txt
      - run:
          name: Install MySQL CLI
          command: |
            mysql -h 127.0.0.1 -u user -ppassw0rd cartsquad
            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="USE cartsquad;"
     
      - run:
          name: Run tests
          command: |
            python cartsquad/manage.py apps.products.tests
            python cartsquad/manage.py apps.carts.tests


workflows:
  version: 2
  build:
    jobs:
      - build
